<a href="https://colab.research.google.com/github/StickySnail/2BDataMaster/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu118


## Introduction to Tensors

### Creating tnesors

PyTorch tensors are created using `torch.Tnsor()` = https://pytorch.org/docs/stable/tensors.html

In [6]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
# number of the dimension
scalar.ndim

0

In [8]:
# Get tensor back as Python int
scalar.item()

7

In [9]:
# Vector
vector = torch.tensor( [7, 7] )
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [16]:
MATRIX[0]


tensor([7, 8])

In [17]:
MATRIX[1]


tensor([ 9, 10])

In [18]:
MATRIX.shape

torch.Size([2, 2])

In [25]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [2,5,6]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [2, 5, 6]]])

In [20]:
TENSOR.ndim

3

In [21]:
TENSOR.shape

torch.Size([1, 3, 3])

In [26]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [2, 5, 6]])

### Random tensors

Why Random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update the random numbers -> look at data -> update the random numbers`

Torch random tensors: https://pytorch.org/docs/stable/generated/torch.rand.html

In [35]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9498, 0.9741, 0.3248, 0.9936],
        [0.3667, 0.6152, 0.8534, 0.1422],
        [0.7540, 0.2305, 0.0792, 0.5759]])

In [38]:
# Create a random tensor with similar shpae to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [43]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [45]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [47]:
ones.dtype, random_image_size_tensor.dtype

(torch.float32, torch.float32)

### Creating a range of tensors and tensors-like

In [54]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])